title: CfA UI Components
name: cfa-ui-components
name_short: ui-comps
program: tax-benefits
repo: codeforamerica/cfa-ui-components
internal: true
subdomain: tax
doppler:
  project: cfa-ui-components
secrets:
  SECRET_KEY_BASE:
    description: Secret key base for Rails key generation
    type: string
services:
  web:
    health_check_path: /up
    subdomain: components
    expose: 8080
    public: true
    ports:
      - 8080
    secrets:
      SECRET_KEY_BASE:
        name: SECRET_KEY_BASE
