title: Rap Sheet Reader
name: cmr-rap-sheet-reader
name_short: cmr-raps
program: clear-my-record
repo: codeforamerica/cmr-rap-sheet-reader
internal: false
services:
  web:
    dockerfile: ./Dockerfile
    context: .
    expose: 3000
    public: true
    health_check_path: /
    ports:
      - 3000
